Added files for homework 1
iboreysha/nodejs-aws-homework pull request #2
Opened 2022-10-13 10:50 UTC by iboreysha

Added files for homework 1

2022-10-15 10:52 UTC, Ivanko5417 requested changes

2022-10-15 10:52 UTC, Ivanko5417 commented on homework-1/task1-1.js
> +  let inputText;
it's better to use 'data' event to subscribe on each chunk of data

2022-10-15 10:52 UTC, Ivanko5417 commented on homework-1/task1-2.js
> +csvtojson()
it's still needed to implement reading, transforming, and writing this file by using streams

2022-10-17 11:35 UTC, iboreysha commented
Test comments

2023-01-17 06:27 UTC, closed without merging